import { Column, Entity, Index, TableInheritance } from 'typeorm';
import { PgBaseEntity } from '../../../bootstrap/database/pg-base.entity';

/**
 * A person at a partner company — the people we correspond with on either side.
 *
 * One table with a `category` discriminator, like `partners` itself:
 * `ClientContactEntity` and `VendorContactEntity` are the children, and their
 * repositories add the filter on their own, so the existing services kept
 * working unchanged.
 *
 * The two sides still name the owning company differently in code
 * (`clientId` / `vendorId`), so both columns exist and each child maps its own.
 * `partnerId` is a Postgres generated column over the two — the one field a
 * combined query can use without caring which side it is. When the services stop
 * using the old names, the two columns collapse into it.
 *
 * A contact may be a record only, or be promoted to a portal login, in which
 * case `userId` links to the membership created for them.
 */
@Entity('partner_contacts')
@TableInheritance({ column: { type: 'varchar', name: 'category' } })
@Index('ix_partner_contacts_org', ['organizationId'])
@Index('ix_partner_contacts_partner', ['partnerId'])
export class PartnerContactEntity extends PgBaseEntity {
  @Column({ type: 'varchar', length: 24 })
  organizationId: string;

  @Column({ type: 'varchar', nullable: true, default: null })
  category: 'client' | 'vendor';

  /**
   * The company this contact belongs to, whichever side it is on. Generated by
   * Postgres from `client_id` / `vendor_id`, so it is read-only here.
   */
  @Column({ type: 'varchar', length: 24, nullable: true, insert: false, update: false })
  partnerId: string;

  @Column({ type: 'varchar' })
  name: string;

  @Column({ type: 'varchar', nullable: true, default: null })
  email: string | null;

  @Column({ type: 'varchar', nullable: true, default: null })
  phone: string | null;

  @Column({ type: 'varchar', nullable: true, default: null })
  designation: string | null;

  /** Auth userId once this contact has a portal login; null = record only. */
  @Column({ type: 'varchar', length: 24, nullable: true, default: null })
  userId: string | null;

  @Column({ type: 'boolean', nullable: false, default: false })
  isDeleted: boolean;
}
